// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewgfwlbtmzqtpjglwwsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Z2Z3bGJ0bXpxdHBqZ2x3d3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODk2OTMsImV4cCI6MjA3MjQ2NTY5M30.Kv5EIR_56npu1nylGxVYCtiKBo1W_gYvepXGfnE1xKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});